const services = [
  {
    id: 1,
    title: "House Cleaning",
    description: "Professional house cleaning for homes and offices.",
    category: "Cleaning",
    price: 5000,
    providerName: "CleanPro Ltd",
    location: "Kigali - Gasabo",
    rating: 4.5,
    available: true,
    image: "/images/cleaning.jpg",
  },
  {
    id: 2,
    title: "Plumbing Repair",
    description: "Fixing pipes, sinks, and water systems efficiently.",
    category: "Plumbing",
    price: 8000,
    providerName: "AquaFix Services",
    location: "Kigali - Kicukiro",
    rating: 4.2,
    available: true,
    image: "/images/plumbing.jpg",
  },
  {
    id: 3,
    title: "Electrical Installation",
    description: "Home electrical installation and maintenance.",
    category: "Electrical",
    price: 10000,
    providerName: "Bright Power",
    location: "Kigali - Nyarugenge",
    rating: 4.7,
    available: false,
    image: "/images/electrical.jpg",
  },

  {
    id: 4,
    title: "Gardening Services",
    description: "Lawn mowing, garden cleaning, and plant maintenance.",
    category: "Gardening",
    price: 7000,
    providerName: "Green Hands",
    location: "Kigali - Gasabo",
    rating: 4.3,
    available: true,
    image: "/images/gardening.jpg",
  },
  {
    id: 5,
    title: "Laundry Services",
    description: "Washing, drying, and ironing clothes professionally.",
    category: "Laundry",
    price: 4000,
    providerName: "Smart Laundry",
    location: "Kigali - Kicukiro",
    rating: 4.1,
    available: true,
    image: "/images/laundry.jpg",
  },
  {
    id: 6,
    title: "Car Wash",
    description: "Interior and exterior car washing services.",
    category: "Automotive",
    price: 6000,
    providerName: "Clean Ride",
    location: "Kigali - Nyarugenge",
    rating: 4.6,
    available: true,
    image: "/images/carwash.jpg",
  },
  {
    id: 7,
    title: "Painting Services",
    description: "House and office painting with quality finishes.",
    category: "Painting",
    price: 15000,
    providerName: "Perfect Paint",
    location: "Kigali - Gasabo",
    rating: 4.4,
    available: true,
    image: "/images/painting.jpg",
  },
  {
    id: 8,
    title: "Computer Repair",
    description: "Laptop and desktop repair and software installation.",
    category: "IT Services",
    price: 12000,
    providerName: "TechCare",
    location: "Kigali - Kicukiro",
    rating: 4.8,
    available: true,
    image: "/images/computer.jpg",
  },
];

export default services;
